#+ summary: Returns the bands
#+ endpoint: http://dbpedia.org/sparql
#+ tags:
#+   - bands
#+ defaults:
#+   - type: http://dbpedia.org/ontology/Band
#+   - genre: http://dbpedia.org/resource/Grunge

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT ?band WHERE {
  ?band a ?_type_iri .
  ?band dbo:genre ?__genre_iri .
  ?band dbo:activeYearsStartYear ?_year_xsd_date .

} 
LIMIT 30
