#+ endpoint: https://api.krr.triply.cc/datasets/vutd88/CooperationDatabankV2/services/CooperationDatabankV2/sparql

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cdo: <http://data.vu.nl/coda/ontology/class#>

SELECT DISTINCT ?v WHERE {
  ?iv rdfs:subClassOf ?_var.
  ?iv a cdo:Variable .
} 
